apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
     github.com/project-slug: 'https://www.apimatic.io/apidocs/backstage-apimatic/v/1_0#/http/step-by-step-tutorial'
  name: my-entity
  namespace: default
spec:
  type: website
  owner: john@example.com
  lifecycle: development
