_type: export
__export_format: 4
__export_source: apimatic.transformer
resources:
- name: Swagger Petstore - OpenAPI 3.0
  _type: workspace
  _id: wrk_c71dacbba19a4cb19a799495f4db39af
  description: >-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about

    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!

    You can now help us improve the API whether it's by making changes to the definition itself or to the code.

    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.


    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_


    Some useful links:

    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)

    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
- name: pet
  _type: request_group
  _id: fld_f3562fbb34a94c828d490054115e18da
  parentId: wrk_c71dacbba19a4cb19a799495f4db39af
  description: Everything about your Pets
- name: store
  _type: request_group
  _id: fld_a49f87e64ad74f7a97fa2422dadd88f8
  parentId: wrk_c71dacbba19a4cb19a799495f4db39af
  description: Access to Petstore orders
- name: user
  _type: request_group
  _id: fld_74cfc1cdc3fd4861a0dbf42226224140
  parentId: wrk_c71dacbba19a4cb19a799495f4db39af
  description: Operations about user
- name: updatePet
  method: PUT
  url: https://petstore3.swagger.io/api/v3/pet
  body:
    mimeType: application/x-www-form-urlencoded
    params:
    - type: text
      name: name
      value: doggie
      disabled: false
    - type: text
      name: photoUrls
      value: '["photoUrls28"]'
      disabled: false
    - type: text
      name: id
      value: '10'
      disabled: false
    - type: text
      name: category
      value: '{"id":1,"name":"Dogs"}'
      disabled: false
    - type: text
      name: tags
      value: '[{"id":109,"name":"name91"}]'
      disabled: false
    - type: text
      name: petStatus
      value: pending
      disabled: false
  headers:
  - name: Content-Type
    value: application/x-www-form-urlencoded
    disabled: false
  _type: request
  _id: req_3a4c9f850317493aa0d829eccd87573f
  parentId: fld_f3562fbb34a94c828d490054115e18da
  description: Update an existing pet by Id
- name: addPet
  method: POST
  url: https://petstore3.swagger.io/api/v3/pet
  body:
    mimeType: application/x-www-form-urlencoded
    params:
    - type: text
      name: name
      value: doggie
      disabled: false
    - type: text
      name: photoUrls
      value: '["photoUrls67"]'
      disabled: false
    - type: text
      name: id
      value: '10'
      disabled: false
    - type: text
      name: category
      value: '{"id":1,"name":"Dogs"}'
      disabled: false
    - type: text
      name: tags
      value: '[{"id":109,"name":"name91"}]'
      disabled: false
    - type: text
      name: petStatus
      value: available
      disabled: false
  headers:
  - name: Content-Type
    value: application/x-www-form-urlencoded
    disabled: false
  _type: request
  _id: req_9acecc4915de45898260c3e554bfad7b
  parentId: fld_f3562fbb34a94c828d490054115e18da
  description: Add a new pet to the store
- name: findPetsByStatus
  method: GET
  url: https://petstore3.swagger.io/api/v3/pet/findByStatus
  parameters:
  - name: status
    value: available
    disabled: false
  _type: request
  _id: req_96f925a9d97c4ee390b879a4ac4f368f
  parentId: fld_f3562fbb34a94c828d490054115e18da
  description: Multiple status values can be provided with comma separated strings
- name: findPetsByTags
  method: GET
  url: https://petstore3.swagger.io/api/v3/pet/findByTags
  parameters:
  - name: tags
    value: '["tags64"]'
    disabled: false
  _type: request
  _id: req_55c4a958ee7a4cbd902eb8220346a016
  parentId: fld_f3562fbb34a94c828d490054115e18da
  description: Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
- name: getPetById
  method: GET
  url: https://petstore3.swagger.io/api/v3/pet/{petId}
  headers:
  - name: api_key
    value: api_key23
    disabled: false
  _type: request
  _id: req_86770505df2c47f0a2894e14819c6488
  parentId: fld_f3562fbb34a94c828d490054115e18da
  description: Returns a single pet
- name: updatePetWithForm
  method: POST
  url: https://petstore3.swagger.io/api/v3/pet/{petId}
  parameters:
  - name: name
    value: name36
    disabled: false
  - name: status
    value: status91
    disabled: false
  _type: request
  _id: req_0559e3171bce4a5cbf3c18f8b8e3be00
  parentId: fld_f3562fbb34a94c828d490054115e18da
  description: Updates a pet in the store with form data
- name: deletePet
  method: DELETE
  url: https://petstore3.swagger.io/api/v3/pet/{petId}
  headers:
  - name: api_key
    value: api_key75
    disabled: false
  _type: request
  _id: req_4bf46bc26cde4d1797b89cce0d399989
  parentId: fld_f3562fbb34a94c828d490054115e18da
  description: delete a pet
- name: uploadFile
  method: POST
  url: https://petstore3.swagger.io/api/v3/pet/{petId}/uploadImage
  body:
    mimeType: multipart/form-data
    params:
    - type: file
      name: body
      value: path/to/file89
      disabled: false
  parameters:
  - name: additionalMetadata
    value: additionalMetadata2
    disabled: false
  headers:
  - name: Content-Type
    value: application/octet-stream
    disabled: false
  _type: request
  _id: req_1c132c3e6d9c49a6ba9d372802c379b5
  parentId: fld_f3562fbb34a94c828d490054115e18da
  description: uploads an image
- name: getInventory
  method: GET
  url: https://petstore3.swagger.io/api/v3/store/inventory
  headers:
  - name: api_key
    value: api_key85
    disabled: false
  _type: request
  _id: req_fb1e1e25d3dd48e299718e174ed63c1f
  parentId: fld_a49f87e64ad74f7a97fa2422dadd88f8
  description: Returns a map of status codes to quantities
- name: placeOrder
  method: POST
  url: https://petstore3.swagger.io/api/v3/store/order
  body:
    mimeType: application/x-www-form-urlencoded
    params:
    - type: text
      name: id
      value: '10'
      disabled: false
    - type: text
      name: petId
      value: '198772'
      disabled: false
    - type: text
      name: quantity
      value: '7'
      disabled: false
    - type: text
      name: shipDate
      value: 2023-05-31T00:00:00Z
      disabled: false
    - type: text
      name: orderStatus
      value: approved
      disabled: false
    - type: text
      name: complete
      value: 'true'
      disabled: false
  headers:
  - name: Content-Type
    value: application/x-www-form-urlencoded
    disabled: false
  _type: request
  _id: req_6e21955a4e99454aba7033f772a17193
  parentId: fld_a49f87e64ad74f7a97fa2422dadd88f8
  description: Place a new order in the store
- name: getOrderById
  method: GET
  url: https://petstore3.swagger.io/api/v3/store/order/{orderId}
  _type: request
  _id: req_2abd3ffc4f684ca7b1c481baca3fa6ce
  parentId: fld_a49f87e64ad74f7a97fa2422dadd88f8
  description: For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
- name: deleteOrder
  method: DELETE
  url: https://petstore3.swagger.io/api/v3/store/order/{orderId}
  _type: request
  _id: req_350587892bfa43af92b3b5601ea4a6de
  parentId: fld_a49f87e64ad74f7a97fa2422dadd88f8
  description: For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
- name: createUser
  method: POST
  url: https://petstore3.swagger.io/api/v3/user
  body:
    mimeType: application/x-www-form-urlencoded
    params:
    - type: text
      name: id
      value: '10'
      disabled: false
    - type: text
      name: username
      value: theUser
      disabled: false
    - type: text
      name: firstName
      value: John
      disabled: false
    - type: text
      name: lastName
      value: James
      disabled: false
    - type: text
      name: email
      value: john@email.com
      disabled: false
    - type: text
      name: password
      value: '12345'
      disabled: false
    - type: text
      name: phone
      value: '12345'
      disabled: false
    - type: text
      name: userStatus
      value: '1'
      disabled: false
  headers:
  - name: Content-Type
    value: application/x-www-form-urlencoded
    disabled: false
  _type: request
  _id: req_2580811d443c4469bd950b55eddfabea
  parentId: fld_74cfc1cdc3fd4861a0dbf42226224140
  description: This can only be done by the logged in user.
- name: createUsersWithListInput
  method: POST
  url: https://petstore3.swagger.io/api/v3/user/createWithList
  body:
    mimeType: application/json
    text: >-
      [

        {

          "id": 10,

          "username": "theUser",

          "firstName": "John",

          "lastName": "James",

          "email": "john@email.com",

          "password": "12345",

          "phone": "12345",

          "userStatus": 1

        }

      ]
  headers:
  - name: Content-Type
    value: application/json
    disabled: false
  _type: request
  _id: req_591ec2c575bb45c6917e1175ac0f3010
  parentId: fld_74cfc1cdc3fd4861a0dbf42226224140
  description: Creates list of users with given input array
- name: loginUser
  method: GET
  url: https://petstore3.swagger.io/api/v3/user/login
  parameters:
  - name: username
    value: username46
    disabled: false
  - name: password
    value: password73
    disabled: false
  _type: request
  _id: req_6d0966a8a2c44c668a5bd328b7841059
  parentId: fld_74cfc1cdc3fd4861a0dbf42226224140
  description: Logs user into the system
- name: logoutUser
  method: GET
  url: https://petstore3.swagger.io/api/v3/user/logout
  _type: request
  _id: req_24080aecdcca4fea8a9e27a39938b593
  parentId: fld_74cfc1cdc3fd4861a0dbf42226224140
  description: Logs out current logged in user session
- name: getUserByName
  method: GET
  url: https://petstore3.swagger.io/api/v3/user/{name}
  _type: request
  _id: req_910ba9effa8b4af287655637682c357d
  parentId: fld_74cfc1cdc3fd4861a0dbf42226224140
  description: Get user by user name
- name: updateUser
  method: PUT
  url: https://petstore3.swagger.io/api/v3/user/{name}
  body:
    mimeType: application/x-www-form-urlencoded
    params:
    - type: text
      name: id
      value: '10'
      disabled: false
    - type: text
      name: username
      value: theUser
      disabled: false
    - type: text
      name: firstName
      value: John
      disabled: false
    - type: text
      name: lastName
      value: James
      disabled: false
    - type: text
      name: email
      value: john@email.com
      disabled: false
    - type: text
      name: password
      value: '12345'
      disabled: false
    - type: text
      name: phone
      value: '12345'
      disabled: false
    - type: text
      name: userStatus
      value: '1'
      disabled: false
  headers:
  - name: Content-Type
    value: application/x-www-form-urlencoded
    disabled: false
  _type: request
  _id: req_6b342e828b33482daf1d39ccd756668a
  parentId: fld_74cfc1cdc3fd4861a0dbf42226224140
  description: This can only be done by the logged in user.
- name: deleteUser
  method: DELETE
  url: https://petstore3.swagger.io/api/v3/user/{name}
  _type: request
  _id: req_957b816dc4eb485db3297b964be8b88b
  parentId: fld_74cfc1cdc3fd4861a0dbf42226224140
  description: This can only be done by the logged in user.
